# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('device_id', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('gpio', models.IntegerField()),
                ('state_change', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('device_id', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('state', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
