# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HAB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('device_id', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('gpio', models.IntegerField()),
                ('error', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
